cookietemple_version: '1.2.4 # <<COOKIETEMPLE_NO_BUMP>>'
domain: cli
language: python
project_slug: acdh-handle-pyutils
project_slug_no_hyphen: acdh_handle_pyutils
template_version: '1.1.0 # <<COOKIETEMPLE_NO_BUMP>>'
template_handle: cli-python
github_username: csae8092
creator_github_username: csae8092
is_github_repo: false
is_repo_private: false
is_github_orga: false
full_name: Peter Andorfer
email: peter.andorfer@oeaw.ac.at
project_name: acdh-handle-pyutils
project_short_description: Utility functions to interact with handle.net API
version: 0.1.0
license: MIT
command_line_interface: Click
testing_library: pytest
